import os
import sys

def setVariables():
    print("Setting Variables for execution")
    os.environ['title'] = 'Company Name Solutions Pvt Ltd'
    os.environ['title2'] = 'Address Line Item 1'
    os.environ['title3'] = 'Address Line Item 2'
    os.environ['title4'] = 'Company Email'
    os.environ['title5'] = 'Company License'
    os.environ['title6'] = 'Salary Slip'
    os.environ['desc1'] = 'For the Period of - '
    os.environ['desc2'] = 'Staff Name: '
    os.environ['desc3'] = 'Month Days: '
    os.environ['desc4'] = 'Department: '
    os.environ['desc5'] = 'Leave Days: '
    os.environ['desc6'] = 'Designation: '
    os.environ['desc7'] = 'Extra Days: '
    os.environ['desc8'] = 'Office: '
    os.environ['desc9'] = 'Present Days: '
    os.environ['center'] = 'Salary Slip'
    os.environ['left'] = 'Earning'
    os.environ['right'] = 'Deductions'
    os.environ['desc10'] = 'Brake Down'
    os.environ['desc11'] = 'Rs'
    os.environ['desc12'] = 'Basic:          '
    os.environ['desc13'] = 'Misc:           '
    os.environ['desc14'] = 'Gross Amount:   '
    os.environ['desc15'] = 'Deductions:     '
    os.environ['desc16'] = 'Net Salary:     '
    os.environ['desc17'] = 'Prepared by: NAME'
    os.environ['desc18'] = 'Checked by: NAME'
    os.environ['desc19'] = 'Authorised by: NAME'
    os.environ['disc1'] = '*This is Computer generated Slip does not require signature.'
    os.environ['disc2'] = '* Contact us for any details.'
